#!/bin/bash

MYSQL_HOST="localhost"
MYSQL_USER="FAH"
MYSQL_PASS=""
MYSQL_DB="FAH"

set -e

TEMPDIR=$(mktemp -d)
mkfifo $TEMPDIR/out.pipe

exec 3>&1

tee $TEMPDIR/out.log < $TEMPDIR/out.pipe &
pid_out=$!
exec 2>&1 1>$TEMPDIR/out.pipe

exit_handler() {
#  echo "UPDATE updates SET output=LOAD_FILE('$TEMPDIR/out.log') WHERE id=(SELECT MAX(id) FROM updates);" | mysql -h $MYSQL_HOST -u $MYSQL_USER -p $MYSQL_PASS $MYSQL_DB

  exec 1>&3 3>&-
  wait $pid_out
  rm -rf $TEMPDIR
}

trap exit_handler EXIT

cd current_lists

orig_listing=$(ls -l daily_*_summary.txt.bz2)

wget -N http://fah-web.stanford.edu/daily_team_summary.txt.bz2
wget -N http://fah-web.stanford.edu/daily_user_summary.txt.bz2

second_listing=$(ls -l daily_*_summary.txt.bz2)

if [ "$orig_listing" == "$second_listing" ]
then
  echo "Lists are up to date"
  exit 1
fi

team_timestamp=$(bzcat daily_team_summary.txt.bz2 | head -1)
user_timestamp=$(bzcat daily_team_summary.txt.bz2 | head -1)

if [ "$team_timestamp" != "$user_timestamp" ]
then
  echo "Lists don't have matching timestamps"
  echo 1
fi

cd ..

timestamp=$(./convert-date "$team_timestamp")

mkdir -p archive_lists/$timestamp

# next section borrwed from http://forum.kakaostats.com/fahstats/fahstats/scripts/ks2.sh
cp --no-clobber -p  \
    current_lists/daily_*_summary.txt.bz2 \
    archive_lists/$timestamp/


bzcat \
    archive_lists/$timestamp/daily_team_summary.txt.bz2 \
    archive_lists/$timestamp/daily_user_summary.txt.bz2 \
        | ./parse-lists
